version: "3.4"

services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - SCRUM_BACKEND_ConnectionStrings__PostgresDatabase=Host=db;Database=postgres;Username=postgres;Password=postgres
      - SCRUM_BACKEND_Auth__OAuth__AuthorizationUri=https://app.vssps.visualstudio.com/oauth2/authorize
      - SCRUM_BACKEND_Auth__OAuth__TokenUri=https://app.vssps.visualstudio.com/oauth2/token
      - SCRUM_BACKEND_Auth__OAuth__ClientId=FILL_OUT
      - SCRUM_BACKEND_Auth__OAuth__ClientSecret=FILL_OUT
      - SCRUM_BACKEND_Auth__OAuth__Scope=vso.analytics vso.code vso.work
      - SCRUM_BACKEND_Auth__OAuth__RedirectUri=https://tinyurl.com/2p94p683
      - SCRUM_BACKEND_Auth__OAuth__JWTIssuer=app.vstoken.visualstudio.com
      - SCRUM_BACKEND_Auth__OAuth__JWTAudience=app.vstoken.visualstudio.com
      - SCRUM_BACKEND_DevOps__ServerUrl=https://dev.azure.com/vertigis
    volumes:
      - ./backend/src:/app
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=/api
      - NODE_ENV=development
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 30s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: