FROM mcr.microsoft.com/dotnet/sdk:7.0.100-bullseye-slim

ENV DOTNET_ENVIRONMENT=Development

WORKDIR /app
COPY ./src .
RUN dotnet restore

ENTRYPOINT [ "dotnet", "watch", "run", "--urls", "http://*:8080" ]