apiVersion: v1
kind: ConfigMap
metadata:
    name: scrum-backend-database-config
    namespace: scrum-backend
data:
    connectionString: Host=scrum-backend-db-service;Database=postgres;Username=postgres;Password=7p9Zi2FvFm38gvHG5T5V
